import type { Metadata } from "next";
import "./globals.css";
import { MapDomainProvider } from "../../contexts/MapContext";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "../../contexts/UserContext";
import { GroupProvider } from "../../contexts/GroupContext";
import { SessionWrapper } from "@/components/SessionWrapper";
import { SocketProvider } from "../../contexts/SocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <SessionWrapper>
          <SocketProvider>
            <UserProvider>
              <GroupProvider>
                <MapDomainProvider>{children}</MapDomainProvider>
              </GroupProvider>
            </UserProvider>
          </SocketProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
