version: '3.8'
services: 
  postgres:
    image: postgres:latest
    container_name: hopin
    environment:
      - POSTGRES_PASSWORD=hopinc09
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: